class_name Roguelike
extends Node2D

## Lumatical — Roguelike Mode.
##
## Procedurally generated puzzle descent. Each floor is a new puzzle
## generated by PuzzleGenerator. Complete it to descend. Run ends if
## you choose to quit or loop back to menu.

const CELL_SIZE := 64.0
const GRID_W := 12
const GRID_H := 8
const GRID_OFFSET := Vector2(256, 104)

const BEAM_COLOR := BeamSimulator.WHITE
const C_RED   := BeamSimulator.RED
const C_GREEN := BeamSimulator.GREEN
const C_BLUE  := BeamSimulator.BLUE

var _floor := 1
var _score := 0
var _current_level: Dictionary
var _solved := false

# Run mode and seed
# mode: "endless", "daily", "shared"
var _mode := "endless"
var _run_seed := -1

@onready var grid: Grid = $Grid
@onready var beam_layer: BeamLayer = $BeamLayer
@onready var audio: AudioManager = $AudioManager
@onready var status_label: Label = $UI/StatusLabel

var _overlay: ColorRect
var _solve_title: Label
var _next_button: Button


func _ready() -> void:
	grid.position = GRID_OFFSET
	beam_layer.position = GRID_OFFSET
	grid.cell_size = CELL_SIZE
	grid.grid_width = GRID_W
	grid.grid_height = GRID_H
	grid.tools_changed.connect(_on_tools_changed)
	_create_overlay()
	_create_top_bar()
	_load_floor(1)


## Called by menu to set the run mode before scene loads.
static var run_mode := "endless"
static var run_seed := -1


func _enter_tree() -> void:
	_mode = run_mode
	_run_seed = run_seed


# ── Overlay ────────────────────────────────────────────────────────────────────

func _create_overlay() -> void:
	var ui: CanvasLayer = $UI
	_overlay = ColorRect.new()
	_overlay.color = Color(0.004, 0.004, 0.01, 0.0)
	_overlay.set_anchors_preset(Control.PRESET_FULL_RECT)
	_overlay.visible = false
	_overlay.modulate.a = 0.0
	ui.add_child(_overlay)

	var center := CenterContainer.new()
	center.set_anchors_preset(Control.PRESET_FULL_RECT)
	_overlay.add_child(center)

	var vbox := VBoxContainer.new()
	vbox.add_theme_constant_override("separation", 24)
	center.add_child(vbox)

	_solve_title = Label.new()
	_solve_title.text = "◆ FLOOR CLEARED ◆"
	_solve_title.add_theme_font_size_override("font_size", 40)
	_solve_title.add_theme_color_override("font_color", Color(0.0, 1.0, 0.53))
	_solve_title.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	vbox.add_child(_solve_title)

	var subtitle := Label.new()
	subtitle.text = "Descend deeper..."
	subtitle.add_theme_font_size_override("font_size", 18)
	subtitle.add_theme_color_override("font_color", Color(0.7, 0.7, 0.9, 0.8))
	subtitle.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	vbox.add_child(subtitle)

	var btn_wrapper := HBoxContainer.new()
	btn_wrapper.alignment = BoxContainer.ALIGNMENT_CENTER
	vbox.add_child(btn_wrapper)

	_next_button = Button.new()
	_next_button.text = "Descend →"
	_next_button.add_theme_font_size_override("font_size", 20)
	_next_button.custom_minimum_size = Vector2(220, 56)
	_next_button.pressed.connect(_on_next_floor)
	btn_wrapper.add_child(_next_button)

	var quit_btn := Button.new()
	quit_btn.text = "End Run"
	quit_btn.add_theme_font_size_override("font_size", 16)
	quit_btn.custom_minimum_size = Vector2(160, 56)
	quit_btn.pressed.connect(_on_quit_run)
	btn_wrapper.add_child(quit_btn)


func _create_top_bar() -> void:
	var ui: CanvasLayer = $UI

	var menu_btn := Button.new()
	menu_btn.text = "☰ Menu"
	menu_btn.add_theme_font_size_override("font_size", 13)
	menu_btn.custom_minimum_size = Vector2(90, 32)
	menu_btn.set_anchors_preset(Control.PRESET_TOP_LEFT)
	menu_btn.offset_left = 16
	menu_btn.offset_top = 12
	menu_btn.offset_right = 112
	menu_btn.offset_bottom = 44
	menu_btn.pressed.connect(_on_quit_run)
	ui.add_child(menu_btn)


# ── Floor Loading ──────────────────────────────────────────────────────────────

func _load_floor(floor_num: int) -> void:
	_floor = floor_num
	_current_level = PuzzleGenerator.generate(floor_num, _run_seed)
	_solved = false

	grid.sources = _current_level["sources"].duplicate(true)
	grid.targets = _current_level["targets"].duplicate(true)
	grid.blockers = _current_level.get("blockers", []).duplicate(true)
	grid.shadow_blocks = _current_level.get("shadow_blocks", []).duplicate(true)
	grid.chromatic_shades = _current_level.get("chromatic_shades", []).duplicate(true)
	grid.null_emitters = _current_level.get("null_emitters", []).duplicate(true)
	grid.mirror_budget = _current_level.get("mirror_budget", 0)
	grid.prism_budget = _current_level.get("prism_budget", 0)
	grid.filter_budget = _current_level.get("filter_budget", 0)
	grid.splitter_budget = _current_level.get("splitter_budget", 0)
	grid.lens_budget = _current_level.get("lens_budget", 0)
	grid.refractor_budget = _current_level.get("refractor_budget", 0)
	grid.teleporter_budget = _current_level.get("teleporter_budget", 0)
	grid.active_tool = 0
	grid.interactive = true
	grid.mirrors.clear()
	grid.prisms.clear()
	grid.filters.clear()
	grid.splitters.clear()
	grid.lenses.clear()
	grid.refractors.clear()
	grid.teleporters.clear()
	grid._hit_targets.clear()
	grid._destroyed_enemies.clear()
	grid.queue_redraw()

	_create_toolbelt()
	_run_simulation(false)
	_update_status()


# ── Toolbelt (rebuilt per floor since budgets change) ──────────────────────────

var _toolbelt: HBoxContainer
var _tool_buttons: Array = []

const TOOL_NAMES := ["Mirror", "Prism", "Filter", "Splitter", "Lens", "Refractor", "Teleport"]
const TOOL_COLORS := [
	Color(0.0, 0.94, 1.0), Color(1.0, 0.0, 0.9), Color(1.0, 0.9, 0.0),
	Color(1.0, 0.53, 0.0), Color(0.67, 0.4, 1.0), Color(0.5, 1.0, 0.8),
	Color(0.9, 0.5, 1.0),
]


func _create_toolbelt() -> void:
	if _toolbelt:
		_toolbelt.queue_free()
	_tool_buttons.clear()

	_toolbelt = HBoxContainer.new()
	_toolbelt.set_anchors_preset(Control.PRESET_BOTTOM_WIDE)
	_toolbelt.offset_top = -76
	_toolbelt.offset_bottom = -12
	_toolbelt.alignment = BoxContainer.ALIGNMENT_CENTER
	_toolbelt.add_theme_constant_override("separation", 8)
	$UI.add_child(_toolbelt)

	for i in range(7):
		var btn := Button.new()
		btn.text = "[%d] %s" % [i + 1, TOOL_NAMES[i]]
		btn.custom_minimum_size = Vector2(130, 56)
		btn.add_theme_font_size_override("font_size", 14)
		btn.pressed.connect(_on_toolbelt_button.bind(i))
		_toolbelt.add_child(btn)
		_tool_buttons.append(btn)
	_update_toolbelt()


func _update_toolbelt() -> void:
	var budgets := [
		grid.mirror_budget, grid.prism_budget, grid.filter_budget,
		grid.splitter_budget, grid.lens_budget, grid.refractor_budget,
		grid.teleporter_budget,
	]
	var used := [
		grid.mirrors.size(), grid.prisms.size(), grid.filters.size(),
		grid.splitters.size(), grid.lenses.size(), grid.refractors.size(),
		grid.teleporters.size(),
	]
	for i in range(7):
		var btn: Button = _tool_buttons[i]
		if budgets[i] == 0:
			btn.visible = false
			continue
		btn.visible = true
		btn.text = "[%d] %s  %d/%d" % [i + 1, TOOL_NAMES[i], used[i], budgets[i]]
		var col: Color = TOOL_COLORS[i] if grid.active_tool == i else Color(0.5, 0.5, 0.6)
		btn.add_theme_color_override("font_color", col)
		btn.add_theme_color_override("font_hover_color", col.lightened(0.3))


func _on_toolbelt_button(tool_index: int) -> void:
	grid.active_tool = tool_index
	_update_toolbelt()
	grid.queue_redraw()


# ── Simulation ────────────────────────────────────────────────────────────────

func _on_tools_changed() -> void:
	_run_simulation()
	_update_status()


func _run_simulation(play_audio := true) -> void:
	var tools := _build_tools_dict()
	var result := BeamSimulator.simulate(
		Vector2i(GRID_W, GRID_H), tools, grid.sources, CELL_SIZE,
	)
	beam_layer.set_segments(result.segments)
	grid.set_hit_targets(result.hit_targets)
	grid.set_destroyed_enemies(result.destroyed_enemies)

	var was_solved := _solved
	_solved = _check_win(result.hit_targets)
	if _solved and not was_solved:
		audio.play_solve_chord()
		_score += _floor * 10
		_show_solve_overlay()
	elif not _solved and was_solved:
		_overlay.visible = false
		grid.interactive = true


func _build_tools_dict() -> Dictionary:
	var d := {}
	for pos in grid.targets:
		d[pos] = {"type": "target", "color": grid.targets[pos]["color"]}
	for pos in grid.blockers:
		d[pos] = {"type": "blocker"}
	for sb in grid.shadow_blocks:
		d[sb["pos"]] = {"type": "shadow_block", "threshold": float(sb.get("threshold", 0.75))}
	for cs in grid.chromatic_shades:
		d[cs["pos"]] = {"type": "chromatic_shade", "color": cs["color"]}
	for pos in grid.null_emitters:
		d[pos] = {"type": "null_emitter"}
	for pos in grid.mirrors:
		d[pos] = {"type": "mirror", "orientation": int(grid.mirrors[pos])}
	for pos in grid.prisms:
		d[pos] = {"type": "prism", "orientation": int(grid.prisms[pos])}
	for pos in grid.filters:
		d[pos] = {"type": "filter", "color": Grid.FILTER_COLORS[int(grid.filters[pos])]}
	for pos in grid.splitters:
		d[pos] = {"type": "splitter", "orientation": int(grid.splitters[pos])}
	for pos in grid.lenses:
		d[pos] = {"type": "lens", "orientation": int(grid.lenses[pos])}
	for pos in grid.refractors:
		d[pos] = {"type": "refractor", "orientation": int(grid.refractors[pos])}
	var tp_positions: Array = grid.teleporters.keys()
	for pos in grid.teleporters:
		var pair_pos: Vector2i = pos
		for other in tp_positions:
			if other != pos:
				pair_pos = other
				break
		d[pos] = {"type": "teleporter", "pair": pair_pos}
	return d


func _check_win(hit_targets: Array) -> bool:
	if grid.targets.is_empty():
		return false
	for pos in grid.targets:
		if not pos in hit_targets:
			return false
	return true


# ── Status ─────────────────────────────────────────────────────────────────────

func _update_status() -> void:
	if _solved:
		return
	var diff_name := _difficulty_name(_floor)
	var mode_label := _mode.capitalize()
	if _mode == "daily":
		mode_label = "Daily %s" % RunManager.get_daily_label()
	if _mode == "shared" and _run_seed >= 0:
		mode_label = "Shared: %s" % RunManager.encode_seed(_run_seed)
	status_label.text = "%s  |  Floor %d  |  Score: %d  |  %s" % [mode_label, _floor, _score, diff_name]
	_update_toolbelt()


func _difficulty_name(floor_num: int) -> String:
	if floor_num <= 5:   return "Easy"
	if floor_num <= 15:  return "Normal"
	if floor_num <= 30:  return "Hard"
	return "Brutal"


# ── Actions ───────────────────────────────────────────────────────────────────

func _show_solve_overlay() -> void:
	_overlay.color = Color(0.004, 0.004, 0.01, 0.0)
	_overlay.visible = true
	grid.interactive = false
	_overlay.modulate.a = 0.0
	var tween := create_tween()
	tween.tween_interval(0.7)
	tween.tween_property(_overlay, "modulate:a", 1.0, 0.4)


func _on_next_floor() -> void:
	_overlay.visible = false
	grid.interactive = true
	audio.stop_all_tones()
	_load_floor(_floor + 1)


func _on_quit_run() -> void:
	# Submit score before leaving
	if _floor > 1:
		RunManager.submit_score(_mode, _floor - 1, _score, _run_seed)
	get_tree().change_scene_to_file("res://scenes/MainMenu.tscn")


func _unhandled_input(event: InputEvent) -> void:
	if _overlay.visible and event is InputEventKey and event.pressed:
		if event.keycode in [KEY_ENTER, KEY_KP_ENTER, KEY_SPACE]:
			_on_next_floor()
		return

	if event is InputEventKey and event.pressed and event.keycode == KEY_M:
		audio.toggle_mute()
